version: "3.9"

services:
  flask_app:
    container_name: flask_app
    image: ncsmatias/ze-pereira-flaskapi:1.0.0
    build: .
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - flask_db

  flask_db:
    container_name: flask_db
    image: postgres:16.1
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
