"""feat: update add created_at and updated_at columns

Revision ID: 361ca9ae5190
Revises: fa09b814188f
Create Date: 2024-02-14 19:46:17.982352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '361ca9ae5190'
down_revision = 'fa09b814188f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('update_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('update_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
