"""feat: update add created_at and updated_at columns

Revision ID: b92c30a95101
Revises: 952cdf0916bc
Create Date: 2024-02-14 19:51:25.070923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b92c30a95101'
down_revision = '952cdf0916bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('update_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('update_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
